import { FileBase } from 'projen';

/**
 * Files whose purpose note has already been attached (guards against
 * wrapping `synthesizeContent` more than once).
 */
const annotated = new WeakSet<FileBase>();

/**
 * Injects a one-line purpose note into a projen-generated workflow file,
 * placed directly beneath the `~~ Generated by projen` marker so that every
 * generated workflow states what it is for:
 *
 * ```
 * # ~~ Generated by projen. To modify, edit ... and run "npx projen".
 * # Purpose: <text>
 * ```
 *
 * The note is part of the *generated* content: it is added at synth time by
 * wrapping the file's `synthesizeContent`, so it is reproduced on every
 * `npx projen` run and can never drift away from (or be stripped by) a
 * re-synthesis. Projen exposes no supported way to add a header comment to a
 * generated workflow file, and `YamlFile#synthesizeContent` is `protected` -
 * hence the narrow structural override applied to the file instance here.
 *
 * Safe to call more than once on the same file (the note is added only once).
 */
export function noteWorkflowPurpose(
  file: FileBase | undefined,
  purpose: string,
): void {
  if (!file || annotated.has(file)) {
    return;
  }
  annotated.add(file);

  const target = file as unknown as {
    synthesizeContent: (resolver: unknown) => string | undefined;
  };
  const original = target.synthesizeContent.bind(file);
  target.synthesizeContent = (resolver: unknown) => {
    const content = original(resolver);
    if (content === undefined) {
      return undefined;
    }
    // The projen marker (if any) is always the first line; the note goes on
    // the line right after it, above the body of the workflow.
    const newline = content.indexOf('\n');
    if (newline === -1) {
      return content;
    }
    return (
      content.slice(0, newline + 1) +
      `# Purpose: ${purpose}\n` +
      content.slice(newline + 1)
    );
  };
}
